TYPE=VIEW
query=select `db7`.`juniorc`.`ResultatID` AS `RESULTATID`,`db7`.`juniorc`.`UtoverID` AS `UTOVERID`,`db7`.`juniorc`.`3000m` AS `3000M`,`db7`.`juniorc`.`60sec` AS `60SEC`,`db7`.`juniorc`.`Kroppshev` AS `KROPPSHEV`,`db7`.`juniorc`.`Sargeant` AS `SARGEANT`,`db7`.`juniorc`.`Beveglighet` AS `BEVEGLIGHET`,`db7`.`juniorc`.`Year` AS `YEAR` from `db7`.`juniorc` limit 10
md5=873fb9c41f7849e8c2afa9d3a448e193
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-11-10 15:44:19
create-version=2
source=SELECT RESULTATID, UTOVERID, `3000M`, `60SEC`, KROPPSHEV, SARGEANT, BEVEGLIGHET, YEAR\nFROM JuniorC\nLIMIT 10
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `db7`.`juniorc`.`ResultatID` AS `RESULTATID`,`db7`.`juniorc`.`UtoverID` AS `UTOVERID`,`db7`.`juniorc`.`3000m` AS `3000M`,`db7`.`juniorc`.`60sec` AS `60SEC`,`db7`.`juniorc`.`Kroppshev` AS `KROPPSHEV`,`db7`.`juniorc`.`Sargeant` AS `SARGEANT`,`db7`.`juniorc`.`Beveglighet` AS `BEVEGLIGHET`,`db7`.`juniorc`.`Year` AS `YEAR` from `db7`.`juniorc` limit 10
mariadb-version=100505
